name: build-staging
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  # Android
  build_android_staging:
    runs-on: ubuntu-latest
    steps:
      # Preparation
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: android

      # Build
      - run: Write-Output $server.name | Out-File '(Your Path)\Servers.txt' -Append
        working-directory: android
