name: set-version

on:
  workflow_dispatch:
  create:
    branches:
      - 'release/**'

jobs:
  # Android
  set_version:
    runs-on: ubuntu-latest
    steps:
      # Preparation
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false
          working-directory: ios

      - name: Get version from branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"

      - name: Split version
        uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ steps.split.outputs.fragment }}
          separator: '.'
          maxsplit: -1

      - name: Overwrite file
        env:
          BRANCH: ${{ github.ref_name }}
        uses: 'DamianReeves/write-file-action@master'
        with:
          path: version.yml
          write-mode: overwrite
          contents: |
            ---
            major: ${{ steps.branch.outputs._0 }}
            minor: ${{ steps.branch.outputs._1 }}
            patch: ${{ steps.branch.outputs._2 }}

      - name: Set version on Pubspec
        run: bundle exec fastlane bump_build_number
        working-directory: ios

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          force: true
          message: 'Set version to - ${{ steps.split.outputs.fragment }}'
