name: set-version
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  # Android
  build_android_staging:
    runs-on: ubuntu-latest
    steps:
      # Preparation
      - uses: actions/checkout@v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: version.yml
          write-mode: overwrite
          contents: |
            ---
            major: ${{ github.ref_name }}
            minor: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/head/}}
            patch: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/release/}}

            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          force: true
          message: 'Set version to -'

