name: set-version
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  # Android
  build_android_staging:
    runs-on: ubuntu-latest
    steps:
      # Preparation
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: android

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: path/to/file.js
          write-mode: overwrite
          contents: |
            console.log('some contents')
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          force: true
          message: 'Overwritten by Github Actions - ${date}'

