name: set-version

on:
  workflow_dispatch:
  create:
    branches:
      - 'release/*'

jobs:
  # Android
  set_version:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.buildNumber.outputs.code }}
      version: ${{ steps.split.outputs.version }}

    steps:
      # Preparation
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ios

      - name: Get version from branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=version::${BRANCH##*/}"

      - name: Split version
        uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ steps.split.outputs.version }}
          separator: '.'
          maxsplit: -1

      - name: Overwrite file
        env:
          BRANCH: ${{ github.ref_name }}
        uses: 'DamianReeves/write-file-action@master'
        with:
          path: version.yml
          write-mode: overwrite
          contents: |
            ---
            major: ${{ steps.branch.outputs._0 }}
            minor: ${{ steps.branch.outputs._1 }}
            patch: ${{ steps.branch.outputs._2 }}

      - name: Set version on Pubspec
        run: bundle exec fastlane apply_new_version
        working-directory: ios

      - name: Get build number on Pubspec
        id: buildNumber
        working-directory: ios
        run: |
          output=$(bundle exec fastlane get_pubspec_build_number)
          echo "Original output: $output"
          numbers=$(echo "$output" | grep -o '[0-9]\{8,\}')
          echo "Extracted build number: $numbers"
          echo "::set-output name=code::$numbers"

      - name: Bump ios build number
        run: bundle exec fastlane bump_build_number build_number:${{ steps.buildNumber.outputs.code }}

      - name: Commit & Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: '${{ github.ref_name }}'
          commit-message: 'Set version to - ${{ steps.split.outputs.version }}'
          force-add: 'true'
          files: pubspec.yaml version.yml
          name: GitHub Action
