name: set-version
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  # Android
  build_android_staging:
    runs-on: ubuntu-latest
    steps:
      # Preparation
      - uses: actions/checkout@v3

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"

      - name: Overwrite file
        env:
            BRANCH: ${{ github.ref_name }}
        uses: "DamianReeves/write-file-action@master"
        with:
          path: version.yml
          write-mode: overwrite
          contents: |
            ---
            major: ${{ github.ref_name }}
            minor: ${ github.ref_name##*/ }
            patch: ${{ steps.split.outputs.fragment }}

            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          force: true
          message: 'Set version to -'

